# Generated by Django 4.0.6 on 2022-07-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.IntegerField(default=1, verbose_name='portfolio owner'),
        ),
    ]
